### ISSUE TITLE
총기 관련 반지 추가

### ISSUE THREAD

**Issue by longestlegs** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#100]
## 이슈 작성 전 참고사항
1. 아이디어 제안은 게임에 맞지 않는다고 판단되거나 코딩 실력의 한계로 구현이 불가능한 경우 답변 없이 이슈가 닫힐 수 있음을 알려드립니다.
2. 챌린지 관련 아이디어는 받지 않습니다.

## 아이디어 제보(자유롭게 적어 주시면 됩니다.)

총알 데미지 증가 반지
총 정확성 증가 반지
탄창 증가 반지

**Comment by Hoto-Mocha** [comment]
- 총 정확성 증가 반지 : 정확성의 반지
- 총알 데미지 증가 반지 : 저격의 반지, 혹은 강화의 주문서
- 탄창 증가 반지 : 거너 2-5특

굳이 반지로는 추가 안 해도 될 것 같은데?
