### ISSUE TITLE
무기들 밸런스 조정 건의

### ISSUE THREAD

**Issue by YouIG** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#102]
## 이슈 작성 전 참고사항
1. 아이디어 제안은 게임에 맞지 않는다고 판단되거나 코딩 실력의 한계로 구현이 불가능한 경우 답변 없이 이슈가 닫힐 수 있음을 알려드립니다.
2. 챌린지 관련 아이디어는 받지 않습니다.

## 아이디어 제보(자유롭게 적어 주시면 됩니다.)

밸런스 조정이 필요하다고 생각되는 무기들 건의 드립니다. 

1. 창과 방패, 랜스 방패
: 창과 방패의 조합은 참신하지만, 현재는 공격 범위와 방어력 적용이 애매한 방향으로 조합되어 있다고 생각됩니다. 공격 범위는 방패와 같고 방어력 적용은 방어 태세 발동 시에만 적용됩니다. 

또한 사용해본 결과 랜스 방패는 흑요석 방패의 마법 데미지 감소가 적용 안 되는 것으로 보입니다. 

방어력 적용이 방어 태세 발동 시에만 적용되는 것은 기믹상 큰 문제가 없어 보이나 창과 랜스를 조합 무기로 사용했음에도 불구하고 공격 범위가 근접에 한정된다는 것은 어느정도 납득하기 어렵다고 생각됩니다. 

따라서 기본 공격 범위의 증가와 랜스 방패에서 방어 태세 발동 시에는 마법 데미지 방어력 추가를 희망합니다. 

2. 슬러그 계열 산탄총
: 이미 한 번 데미지 상향을 받은 적이 있으나, 여전히 벅샷에 비해 메리트가 적다고 생각됩니다. 

산탄총 특성상 탄약이 1발인데 벅샷은 펠릿 수가 많아 적의 방어 또는 회피를 커버할 수 있지만 슬러그는 빗나갈 시 커버가 불가능합니다. 

또한 슬러그의 저지력으로 적에게 불구를 거는 기믹이 존재하지만 확률이 높지 않아 기대하기는 어렵습니다. 

물론 방어력 무시에 기습까지 가능하여 명중만 한다면 데미지는 괜찮게 나오지만, 이는 그냥 재장전 시간이 1턴인 저격총처럼 되어버려 '슬러그 산탄총'이라는 다른 매력이 없습니다. 

따라서 전체적으로 슬러그 산탄총만의 매력이 부족한 것으로 보이며, 이를 해결하기 위해 불구 확률의 증가 혹은 탄성 효과를 적용하여 슬러그 기믹을 더욱 살려 벅샷과는 차별화된 총기 성능을 보여주기 바랍니다. 

3. 진정한 룬검
: 진정한 룬검의 힘 수치에 따른 공격속도는 절륜하지만 데미지가 굉장히 낮습니다. 

마법이 부여되더라도 특정 마법을 제외한다면 불타는, 관성, 탄성, 도달 등 트롤이 되는 마법이 더 많은데 이 마법 부여의 랜덤성은 게임의 재미요소로 보고 그대로 두더라도 

진정한 룬검 자체에 랜스와 같이 방어력 무시 효과를 넣어 부족한 데미지를 커버할 수 있으면 좋을 것 같습니다. 

힘의 반지 등으로 초과 힘수치에 따른 추가 공격력을 얻긴 하지만 그래도 부족한 공격력이 아쉽다고 생각됩니다.

**Comment by Hoto-Mocha** [comment]
1, 2번은 부분적으로 동의하는데 3번은 동의를 못하겠음. 검투사라는 충분한 딜 보완 수단이 있기 때문. 공속이 4배로 증가하는 6강에서 판금 10강이면 전부 명중했을 때 기준으로 1.25턴마다 딜 높은 메치기 쓰기가 가능함
그게 아니더라도 공격 속도가 증가하는 강화수치(1, 3, 6, 10, 15)간의 강화 공백이 있는데, 공백 사이에 남는 강줌을 더 좋은 마법부여 뽑기에 투자할 수 있다고 봄. 예를 들어 무기에 12강을 할 계획이었다면 강줌 2장은 마부에 바르는 식으로.

**Comment by Hoto-Mocha** [comment]
일단 동의하는 부분에 있어서 수정을 진행했으니 그래도 정 이해가 안 되면 다시 이슈 작성 바람

**Comment by YouIG** [comment]
확인했습니다.
