### ISSUE TITLE
1.27.1 버전 이전에 생성된 세이브 구동 불가

### ISSUE THREAD

**Issue by IAMAMAN1** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#103]
## 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 체크박스가 있는 문항의 경우 체크를 원하시면 [ ] 를 [x]로 바꿔 주시면 됩니다.
5. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
6. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
7. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.25.0) : 1.27.1
- [x] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요?
- [x] 게임에 크래시가 발생했나요(튕겼나요)?
- 버그 내용 : 1.27.0 버전까지는 잘 구동되던 세이브가 업데이트 직후 구동되지 않음, 이후 생성한 세이브는 잘 구동됨
- 버그 발생 조건('모름'일 경우 빠른 해결에 어려움이 있습니다) : ~1.27.0 버전까지에서 생성된 세이브일 경우에만 되는 것으로 보임. 드랍 테이블 변경 때문인지 또는 다른 이유인지 검토 부탁

## 선택 정보
- 스크린샷 첨부
![Capture+_2022-01-10-17-33-35](https://user-images.githubusercontent.com/97435105/148737511-d8777f30-dcee-40fe-b4de-66f8b8aa65b5.png)
상기의 스크린샷은 1.27.0 버전에 생성 및 플레이했던 세이브
![Capture+_2022-01-10-17-33-45](https://user-images.githubusercontent.com/97435105/148737545-2df35c80-fe9f-490c-afcc-efdf92c0c7d4.png)
이어하려 하자 위의 이미지처럼 멈춰버림, 남아 있던 다른 두 세이브도 동일했음

**Comment by Hoto-Mocha** [comment]
드랍 테이블을 통째로 없애 버려서 그런 것 같음. 이슈 작성 전 참고사항 1번 확인 바람

**Comment by IAMAMAN1** [comment]
그럼 세이브 3개 전부 버려야 함? 도박사 파밍중/다깨놓고 클리어 보류한거/깨다가 멈춘거 이렇게 3개였는데 후진도 못하고 버려야겠네

**Comment by Hoto-Mocha** [comment]
버리는 수밖에 없지...
