### ISSUE TITLE
1.27.0 버전 버그제보 (1.27.2버전은 아니지만 제보가 없어서..)

### ISSUE THREAD

**Issue by ekdnsfhem** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#107]
## 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 체크박스가 있는 문항의 경우 체크를 원하시면 [ ] 를 [x]로 바꿔 주시면 됩니다.
5. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
6. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
7. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.25.0) :  1.27.0
- [x] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? 아니오, 1.27.0버전 세이브입니다.
- [ ] 게임에 크래시가 발생했나요(튕겼나요)? 아니오
- 버그 내용 : 탈바꿈의 주문서로 광범위한 탐색으로 바꿀시 특성적용 안됨
- 버그 발생 조건('모름'일 경우 빠른 해결에 어려움이 있습니다) : 
식물학자 - 보물 사냥꾼 플레이, '탈바꿈의 주문서'로 2개 찍은 '싹 틔우기'을 도적 2티어 특성 '광범위 탐색'으로 교체시 탐색범위가 7x7로 늘지않고 5x5 그대로임

## 선택 정보
- 스크린샷 첨부
27

**Comment by Hoto-Mocha** [comment]
이건 녹픽던 문장 자체의 표기문제라 버그는 아님

**Comment by Hoto-Mocha** [comment]
도적이 원래 5×5에서 1칸 증가(특성효과)로 7×7이 되는건데, 탈바꿈의 주문서가 나왔지만 여전히 특성 설명은 해당 특성을 원래부터 가지고 있는 직업을 기준으로 쓰여 있어서 그럼
그러니3×3짜리가 특성을 찍으면 1칸 증가해서 5×5가 되는거지
따라서 기능의 문제는 없음. 녹픽던 문장 자체의 문제야
예전에 번역사이트에 그거 관련해서 내가 에반한테 물어봐둔 거 있는데 아직 답이 안 왔음

**Comment by Hoto-Mocha** [comment]
문제의 문장은 이것들 말고도 많음. 사냥꾼 2-1특이 '[사냥꾼은] 음식을 먹으면 신속을 얻습니다' 이렇게 쓰여 있는 것 등등

**Comment by Hoto-Mocha** [comment]
정리하자면 탈바꿈의 주문서 추가로 인해서 해당 특성을 다른 직업도 쓸 수 있게 되었는데, 설명 문장은 여전히 특정 직업 전용으로 적혀 있는 게 녹픽던에서 수정이 안 되었다는거지

**Comment by ekdnsfhem** [comment]
오 생각해보니까 도적빼고는 3x3이 기본이구나7x7로 늘어나는게 아니라 2칸 늘어나는걸로 생각하면 적용된거네! ㄱㅅㄱㅅ
