### ISSUE TITLE
사냥꾼 영혼의 활 고급진화 신규 무기 관련 버그 제보 및 건의 사항

### ISSUE THREAD

**Issue by YouIG** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#109]
## 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 체크박스가 있는 문항의 경우 체크를 원하시면 [ ] 를 [x]로 바꿔 주시면 됩니다.
5. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
6. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
7. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.25.0) : 1.28.0
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요?
- [ ] 게임에 크래시가 발생했나요(튕겼나요)?

- 버그 내용 : 고급진화로 만든 자연의 활에 마법 부여 및 증강의 돌 사용 불가능. 마법 부여는 마부돌, 마부줌 모두 안 됨. 일단은 자연의 활만 확인하였으나 나머지 무기들도 같은 문제 발생할 것으로 예상. 

영혼의 활에는 마법 및 증강이 가능하기 때문에 설계 의도와 다른 버그일 것으로 예상되어 제보합니다.  

- 버그 발생 조건('모름'일 경우 빠른 해결에 어려움이 있습니다) : 모름. 

- 건의 사항 : 이번 업데이트를 통해 탄피 제작에 소모되는 액체금속을 줄여 이제는 고급진화 하나를 만드는데 총 액체금속 185, 송진 3개와 21의 연금술 에너지가 들어가게 됩니다.
 
액체금속 요구량이 줄어든 것은 대단히 환영할만한 일이나, 고급진화에는 오로지 마법막대를 통해서만 얻을 수 있는 송진이 무려 3개나 들어가기 때문에 현재의 영혼의 활 고급진화 확률인 50%는 다른 고급진화 무기들에 비해 자원 소모량 대비 기대값이 너무 낮아 제작에 어려움이 큽니다. 

비단 액체금속의 부족보다는 마법막대를 송진으로 바꾸는데 필요한 5의 연금술 에너지와 투척무기를 액체금속으로 전환하는데 소모되는 2~4의 연금술 에너지도 모두 고려한다면 여전히 고급진화 제작에 소모되는 자원량이 꽤나 크다는 것을 알 수 있습니다. 

결국 지옥 계층 초반 정도에 도달해서야 50% 확률의 자연의 활 하나를 만들기 위해 3번의 시도 끝에 성공하였는데, 지깎노를 통해 얻은 1강 막대에서 송진 4개, 수정 상자 등 기타 필드 드랍으로 먹은 노강 막대 3개에서 송진 6개를 얻어 총 10개의 송진 중 9개를 사용하여 제작하였습니다. 소모된 액체금속은 총 555이고 상점에서 판매되는 투척무기를 모두 구매하였어도 부족함을 느꼈습니다. 

상점에서도 무조건 판매되는 투척무기에 비해 상대적으로 마법막대의 드랍률과 수급처가 적고 고급진화 제작과정에 소모되는 연금술 에너지가 결코 적지 않아 50% 확률은 체감상 너무 낮다고 느껴졌습니다. 게다가 후반의 상점에서 판매되는 투척무기와 마법막대의 가격도 엄청나기 때문에 더더욱 진입장벽이 높습니다. 

자연의 활을 사용해 본 결과 성능은 고급진화를 사용한 총기나 기타 6티어 무기와 기존 영혼의 활에 비해 월등하다고 느껴지지는 않았는데, 강화도 불가능하며 대미지 보다는 추가적인 효과가 부여되는 정도이므로 고급진화 무기로는 애매한 성능이라 생각됩니다.

또한 해로운 식물 효과가 '랜덤'으로 발동하며 이러한 효과들이 100% 확률로 발동하는 것이 아니고 상황에 따라서는 불, 얼음 등 트롤할 가능성도 충분하다고 느꼈습니다.  

기존 직업 전용 장비에 고급진화를 통한 바리에이션이 추가되는 것은 굉장히 만족스러웠지만, 고급진화를 사용할만한 성능은 아니라는 점과 영혼의 활이 타 직업은 사용할 수 없는 식물학자의 삽과 마찬가지로 사냥꾼 고유의 무기라는 점 그리고 50%라는 확률의 존재로 인해 사용성이 애매하다고 생각됩니다.

고급진화에 소모되는 자원의 경우 여전히 약간 많다고 느껴지긴 하지만 기존 총기와 근접 무기들의 6티어 무기 성능을 생각한다면 밸런스적인 측면에서 큰 문제가 없다고 생각되오나, 영혼의 활의 고급진화 확률은 성능에 비해 확실히 너무 낮다고 생각됩니다.  

따라서 식물학자의 야전삽과 마찬가지로 사냥꾼 직업 고유 최종 무기 정도로 취급하고, 언제든지 원할 때 만들 수 있는 장비 정도로 생각해 확률을 90%나 100%로 조정하는 것을 건의드립니다.

어차피 한 게임을 진행하면서 시도할 수 있는 고급진화는 부유의 반지 등으로 자원을 수급하지 않는 이상 자연스럽게 2~3번 정도로 한정되기 때문에 원하는 고급 영혼의 활을 얻기 위해 고급진화를 반복해서 쓰기도 애매하고 무기의 성능을 고려해 본다면 100%의 확률을 적용해도 괜찮을 것이라 생각합니다. 

감사합니다. 

## 선택 정보
- 스크린샷 첨부

**Comment by Hoto-Mocha** [comment]
그럼 100%로 하는 대신 성능 낮은 활과 높은 활의 확률을 다르게 하는 방식으로 만들겠음

**Comment by Hoto-Mocha** [comment]
반영완료
