### ISSUE TITLE
자연의 활 저격수 버그?

### ISSUE THREAD

**Issue by Fullhit** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#112]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.28.1) : 1.28.1
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? 
- [ ] 게임에 크래시가 발생했나요(튕겼나요)?
- 버그 내용 : 활이 진화하면 투척무기 이후 사용하는 특별한 공격이 사용 불가능해지는 것으로 추정됨. 확인한건 자연의 활밖에 없음.
- 버그 발생 조건 : ``

## 선택 정보
- 스크린샷 첨부

**Comment by Hoto-Mocha** [comment]
수정완료
