### ISSUE TITLE
특수 총기 (로켓 발사기, 화염 방사기) 및 유탄 발사기 밸런싱 아이디어 제시

### ISSUE THREAD

**Issue by YouIG** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#123]
## 이슈 작성 전 참고사항
1. 아이디어 제안은 게임에 맞지 않는다고 판단되거나 코딩 실력의 한계로 구현이 불가능한 경우 답변 없이 이슈가 닫힐 수 있음을 알려드립니다.
2. 챌린지 관련 아이디어는 받지 않습니다.

## 아이디어 제보(자유롭게 적어 주시면 됩니다.)

현재 총픽던에는 로켓 발사기, 화염 방사기, 입자포, 유탄 발사기와 같이 특수한 기믹을 가진 총기들이 존재합니다. 

이번 29.2 업데이트를 통해 유탄 발사기는 완전히 보조 수단 총기로 전환 되었고, 그 역할을 훌륭히 수행하며 완벽한 밸런싱이었다고 생각합니다. 

하지만 나머지 로켓 발사기, 화염 방사기는 조금 메롱한 성능을 갖고 있는데 이들에 관한 밸런싱 아이디어를 건의합니다. 

**- 유탄 발사기 -**
이번 29.2 버전에 새롭게 업데이트 된 유탄 발사기는 취약, 연막, 마비를 사용하는 보조 수단으로써 훌륭한 역할을 수행하지만 장전 타이밍이 30, 50, 100턴으로 꽤나 깁니다. 

따라서 게임 플레이 도중 장전 타이밍을 놓치는 경우가 종종 있는데, 혹시 구현 가능하다면 편의성 개선을 위해 쿨타임이 차면 자동으로 장전되는 시스템을 적용한다면 좋을 것 같습니다. 

또한 각 무기 툴팁에 새롭게 적용된 취약, 연막, 마비의 설명 기입이 필요해 보입니다. 

**- 로켓 발사기 -**
4연장 로켓은 5티어 무기임에도 불구하고 강화를 해도 근접 공격력이 0-10으로 고정되어 있는데 이것이 버그인지, 의도된 것인지 궁금합니다. 

혹시 의도된 것이라면 로켓 발사기는 사실상 거너 이외의 다른 직업들은 사용 불가능하다고 생각되는데

거너는 그나마 3-1 특성으로 적과 근접 교전시 공격력을 보정 받을 수 있지만,

로켓 발사기는 총기이므로 증강의 돌로 공속, 공격력을 늘릴 수 없고 탄으로도 다른 개조가 불가능하기 때문에  

0-10 고정 공격력으로는 다른 직업들이 활용하기에는 굉장히 어려운 무기라고 생각합니다.  

신속의 반지가 없다면 명중률이 존재하기 때문에 빗나가는 경우 적과의 근접 전투가 불가피 합니다. 

이런 상황에서 0-10 고정 공격력은 5티어 총기임에도 불구하고 납득하기 어려운 기믹이라고 생각합니다. 

또한 대전차 로켓이 4연장 로켓에 비해 얻는 메리트는 대미지 밖에 없는데, 4연장 로켓은 탄이 4발이지만 대전차 로켓은 탄창이 한 발이므로 빗나갈 경우 손해가 막심합니다.

폭발 대미지에는 명중 시스템이 어떻게 적용되는지 모르지만, 적을 직접 맞추지 않고 옆에 쏴도 빗나감이 뜨는 것을 보면 보정이 필요할 것 같습니다. 

따라서 대전차 로켓은 4연장 로켓에 비해 추가 정확도를 부여하는 밸런싱이 필요하다고 느껴집니다. 

그리고 대전차 로켓은 적과 자신 모두에게 엄청난 대미지를 줄 수 있기 때문에 하이리스크 하이리턴 기믹을 유지하는 것에는 의의가 없지만

4연장 로켓은 유탄 발사기가 보조형 무기로 전환되었으므로 조금 더 범용적인 폭발형 무기로 컨셉을 바꾸고 전체적인 대미지를 줄이고 또한 자가 피해 대미지도 줄여 굳이 신속의 반지가 없어도 사용할 수 있는 조금 더 접근성 있는 무기가 되면 좋을 것 같습니다. 

로켓 발사기는 다른 특수 무기인 화염방사기나 입자포처럼 탄을 사용한 개조가 없다는 점이 조금 아쉽지만 고급진화인 대전차 로켓은 말 그대로 하이리스크 하이리턴의 극강의 폭발형 원거리 무기 컨셉을 유지하고, 4연장 로켓은 조금 더 접근성 좋은 총기로 전환하는 것을 건의드립니다. 

**- 화염 방사기 -**
입자포는 충전의 반지가 있을 경우 대미지가 상승하는 추가 기믹이 적용되었지만 화염 방사기는 기믹이 조금 부족합니다. 

로켓 발사기, 입자포와 함께 낮은 드랍율을 갖는 특수 총기 포지션을 갖고 있다고 생각하는데, 

화염 방사기는 마치 화염 막대처럼 모든 것을 불태우기 때문에 사용이 굉장히 어렵습니다. 

따라서 현재의 탄 개조를 얼음, 번개 등 속성 변경 기믹을 추가하여 플레이어의 선택에 따라 바꿀 수 있도록 만들어 사용할 수 있으면 좋을 것 같습니다. 

혹은 아예 아이템은 불태우지 않게 만드는 것도 괜찮아 보이지만, 이는 화염 막대를 생각하면 애매한 성능일 것 같고 로그라이크에 맞지 않을 것으로 생각됩니다. 

결론은 단순 화염 공격으로는 모든 것을 태워버려 사용이 매우 어렵고, 또한 로켓 발사기와 마찬가지로 접근성이 좋지 않습니다. 

밸런싱이 가장 어려운 무기라고 생각되는데, 그래도 약간의 개선이 필요하다고 느껴집니다.

**Comment by Hoto-Mocha** [comment]
답변 하기에 앞서 건의 준 내용에 대해선 부분적으로 동의한다는 점을 밝힘.

이런 건의를 받을 때마다 항상 느끼는 건데, 무기를 쓰다가 단점 좀 보인다고 __무기 하나만으로 완전체를 만들어주길 바라는 경우__ 가 굉장히 많아. 이것 때문에 스트레스를 많이 받고 있고.
내가 추구하는 방향성과는 너무 다름.

녹픽던은 __다른 아이템, 직업과 시너지를 보면서 어떤 아이템이 가진 단점을 줄이고 장점을 이끌어냄으로써 높은 성능을 만들어내는 게임__ 이지 __직업, 현재 템 상황에 관계없이__ 아무거나 쓰고 싶은 무기를 쓰면서 강화 몰빵하면 마냥 쎄져서 막 썰어버리는 게임이 아니야.
적어도 난 그렇게 생각하고 있고, 그런 방향성을 추구하고 있어.
그 점을 좀 고려해줬으면 좋겠어.

1. 4연장 로켓의 근접 공격력은 의도치 않은 게 맞음. 원래라면 __화염방사기 정도의 근접 공격력__ 을 가져야 해

2. 로켓 발사기든 뭐든 이제 기습을 할 수 있게 되면서 명중률 관련 문제는 해결되었다고 봐. 리스크는 다른 부분으로 보완하는거지 로켓만 뻥뻥 쏜다고 모든 게 해결되어서는 안 된다고 생각해. __리스크에 대한 대비 없이 하이 리스크 하이 리턴 무기를 사용하는 건 바람직하지 않다고 봐.__
물론 로켓 발사기의 힘 요구 수치 22는 내가 써 봐도 생각보다 쓰기 힘들었기에 그건 다시 20으로 낮출 예정이야. 주무기로 쓰기 쉬운 다른 6티어 총기에 비해 고급 진화 시 기믹도 크게 변하고 쓰기 까다로운건 사실이라서.

3. 입자포는 데미지 관련 기믹이 있지만 __일렬로 서 있는 게 아닌 일대 다수의 상황__ 에 취약하고, 화염 방사기가 만들어내는 불의 경우 대답은 2번과 같아.
화염 방사기의 데미지 자체는 입자포보다는 낮은 편이지만 __각도에 관계 없이__ 넓은 지역에 100% 명중률로 피해를 주는 게 가능하고, 오늘 내가 실제로 써 본 결과 5강 화염 방사기만 줄창 쏴도 적들이 녹는 걸 볼 수 있었어.
장탄수가 __두 배__ 인 이유가 있어.

4. 총픽던 무기들 자체가 __전체적으로 오버스펙__ 임을 감안했을 때 더 이상의 버프는 바람직하지 않아 보여.

5. 화염 방사기에 속성 변경 기믹은 아쉽지만 추가할 생각이 없어. __화염이라서__ 하이 리스크 하이 리턴인 거지 이외의 것들은 그냥 하이 리턴이라고 생각해.
그리고 전부터 입자포 관련 데미지 기믹은 너프할 생각이었어

6. 명중률 관련해서는 패널티 없는 특성(거너 2-3)도 있어.
더 필요하면 정확성의 반지를 찾아야지, 무기를 버프하는게 과연 옳은 선택일까 싶네
4연장 로켓은 하이 리스크 하이 리턴 무기에 속하지만 4발 장전이라는 나름의 돌파구가 이미 존재해. 
따라서 난 첫발에 못 죽여도 두발 세발 있으면 괜찮다고 봐
그리고 2번에서도 얘기했지만 명중률 관련이든 근접했을 때 대처법이든 위기에 대한 대비가 안 되어 있으면 __로켓류를 주무기로 안 드는게 맞아.__
신반, 모래시계, 에테르 사슬 중 단 하나도 없이 저격반에 몰빵하는 저격수를 생각하면 돼
그래서 __모든 직업이 아무때나 사용할 수 있는 무기__ 는 나는 반대야. __저격의 반지__ 를 생각해 보면 이해가 쉬울듯
무기가 그 게임에서 하나만 나오는 것도 아니고, __다양한 선택지가 있는데(심지어 변줌도 있고)__ 굳이 리스크가 큰 무기를 고르는 건 좀...

7. 유탄 발사기 능력 관련해서는 설명을 추가할 계획이야.
그리고 쿨타임이 끝나자마자 재장전을 __해야만 하는 이유__ 도 없고, 심지어 __재장전 시간 자체도 1턴__ 이라 언제든지 부담없이 장전이 가능하기에 자동장전은 굳이? 싶네

8. 화염 방사기로 만드는 불의 위치에 대해는 화염막대와 같이 플레이어 앞에는 안 생기게 하는 기믹을 추가해볼 생각이야. 구현이 가능할진 모르겠지만.

9. 가장 중요한 점은 이 게임이 __로그라이크__ 라는 점이야.
운빨겜에서 확정적인 요소를 늘리는 건 정말로 바람직하지 못하다고 봐.

**Comment by YouIG** [comment]
먼저 제작자의 무기 설계 의도와 게임의 방향성에 관하여 장문의 답변을 주셔서 감사합니다. 

그동안 두어 번 정도 총픽던의 밸런싱에 관해 건의 글을 작성했었는데, 이전 글과 이번 글 모두 제작자의 설계 의도를 무시하는 듯한 말투와 일방적인 버프만 요구했던 점을 사과드립니다. 

제가 건의드렸던 내용들은 전부 어디까지나 총픽던을 즐기는 플레이어 개인의 희망사항이었으며, 단지 제딴에는 보다 재미있는 게임을 위해 순수한 의도로 의견을 제시했다고 생각했는데, 다시 읽어보니 아무래도 제작자의 의견을 무시하는 듯한 말투로 글을 작성한 것 같습니다. 이에 관해 깊이 사과드립니다. 

다시 한 번 말씀드리지만 제작자의 설계 의도를 무시할 생각은 전혀 없었으며, 혹여 그렇게 느끼셨다면 정말 다시 한 번 깊이 사과드립니다.. 이에 관하여 제작자께서 많은 스트레스를 받지 않았으면 좋겠습니다.

아무래도 밸런싱 건의에 앞서 이 게임이 부당한 상황이 판치는 '로그라이크' 게임이라는 대전제를 간과했던 것 같습니다. 

완벽한 무기를 들고 단순 강줌 몰빵 메타로 클리어 할 수 있는 게임은 저 역시 바람직하지 못하다고 생각하며, 제작자의 답변에서 설명된 무기 설계 의도에 관해 전적으로 공감하고 동의합니다. 

재미있는 게임에 감사드리며 항상 응원하고 있습니다. 앞으로도 잘 부탁드립니다.

**Comment by Hoto-Mocha** [comment]
사과받으려고 한 말은 아닌데, 이해해 줘서 고마워
