### ISSUE TITLE
[공지] 업데이트 내역은 릴리즈에서 확인 가능

### ISSUE THREAD

**Issue by Hoto-Mocha** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#142]
ㅈㄱㄴ

**Comment by sjsxmd** [comment]
there is a bug on wizard`s 3-5,plz check that

**Comment by Hoto-Mocha** [comment]
> there is a bug on wizard`s 3-5,plz check that

what is the name of subclass?

**Comment by Hoto-Mocha** [comment]
> there is a bug on wizard`s 3-5,plz check that

oh its engineer's 3-6, I checked

**Comment by sjsxmd** [comment]
yes😹3-6

**Comment by sjsxmd** [comment]
bug：수호의마법서  can't give 3 turns evasion when read it

**Comment by Hoto-Mocha** [comment]
> bug：수호의마법서 can't give 3 turns evasion when read it

you mean, the summoned mirror images from spellbook don't get the Evasive Move buff?

**Comment by sjsxmd** [comment]
yes

**Comment by Hoto-Mocha** [comment]
> yes

![Screenshot_20220220-131539.jpg](https://user-images.githubusercontent.com/76470428/154828204-5973ec04-7050-4f0f-a3b1-93cd541b8398.jpg)
![Screenshot_20220220-131544.jpg](https://user-images.githubusercontent.com/76470428/154828207-8f9c158b-1c3f-442d-9553-ab6691cc44de.jpg)

It works well, though.

**Comment by sjsxmd** [comment]
😹I see，the buff  is give to mirror image
