### ISSUE TITLE
기사 1-5특성

### ISSUE THREAD

**Issue by chomit** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#154]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.28.1) : 1.41.1
- 
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요?
- [ ] 게임에 크래시가 발생했나요(튕겼나요)?
- 버그 내용 : 첫타격이 아님에도 불구하고 기사 1-5특성을 발동
- 버그 발생 조건 : 1-5를 안찍은 상태에서 몬스터를 공격 후 1-5를 찍고 몬스터를 공격하면 아드레날린을 얻음

## 선택 정보
- 스크린샷 첨부
- 
![Screenshot_20220225-084807](https://user-images.githubusercontent.com/100388373/155626935-5e64d1ca-163a-4609-be4f-63414749011f.jpg)

![Screenshot_20220225-084813](https://user-images.githubusercontent.com/100388373/155626920-e93e110b-8ced-4e83-8c5c-b666a6666e11.jpg)

![Screenshot_20220225-084822](https://user-images.githubusercontent.com/100388373/155626801-03b4c1be-fc37-4bc0-9f0b-8cfbc5e63999.jpg)

**Comment by Hoto-Mocha** [comment]
이건 원래 그런 거라 버그가 아닌데?
특성을 얻기 전에 때렸어도 특성을 얻고 나서 처음 공격하는 적이잖아
녹픽던에 있는 다른 처음 공격 시 추가 효과류 특성도 다 저럴 거야

**Comment by Hoto-Mocha** [comment]
문장 자체에 완벽하게 오류가 없는 건 아니지만 녹픽던도 같은 시스템을 사용하는 거라서 딱히 문제될 건 없는 것 같아
