### ISSUE TITLE
버그 제보

### ISSUE THREAD

**Issue by DDukBBul** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#175]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.28.1) : 1.20_based_2.7.3 안드로이드 버전
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? 아닙니다
- [x] 게임에 크래시가 발생했나요(튕겼나요)? 예
- 버그 내용 :
- 1. 인터페이스크기를 전체모드(PC모드) 로 이용하다가 모바일모드로 바꾸면 크래쉬
- 2. 거너 3-1특성(시가전) 이 불필요하게 사용되는 경우 발생 
- 버그 발생 조건 : 
- 1. 정확한 발생조건 알 수 없음. 크래쉬가 일어나는 경우도 있고 정상적으로 작동하는 경우도 있음
- 2. 스크린샷 확인 바람

## 선택 정보

- 스크린샷 첨부
![쏘기전](https://user-images.githubusercontent.com/102169238/160224285-298375a0-b9c8-49d2-bc74-fd181735de68.png)
![쏜 후](https://user-images.githubusercontent.com/102169238/160224286-477448cb-a0c3-4f71-9725-565e8b365b6b.png)

**Comment by Hoto-Mocha** [comment]
버그 조건이 하나같이 애매해서 당장 해결하기에는 뭐하네
일단 보류해두겠음

**Comment by Hoto-Mocha** [comment]
시가전 특성의 경우 원인은 파악했는데 해결이 안 돼서 특성에 설명 추가하고 그냥 놔두기로 했음

**Comment by Ziraltul** [comment]
1.2.1_based_2.10.0 안드로이드 버전
 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? 아닙니다
 게임에 크래시가 발생했나요(튕겼나요)? 예

연금술 도구상자로 자동소총을 재료 바로 불러와주는 화살표 눌러서 제작하려고 하니 화살표 누르자마자 팅기고 액체금속이 다 없어짐. 다른재료는 무사. 연금술 솥에서 팅기는지는 모름. 재료템 장착 안했었고 강화도 안되있었음. 그냥 수동으로 넣으서 만들면 잘 되긴 함.

**Comment by Hoto-Mocha** [comment]
> 1.2.1_based_2.10.0 안드로이드 버전 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? 아닙니다 게임에 크래시가 발생했나요(튕겼나요)? 예
> 
> 연금술 도구상자로 자동소총을 재료 바로 불러와주는 화살표 눌러서 제작하려고 하니 화살표 누르자마자 팅기고 액체금속이 다 없어짐. 다른재료는 무사. 연금술 솥에서 팅기는지는 모름. 재료템 장착 안했었고 강화도 안되있었음. 그냥 수동으로 넣으서 만들면 잘 되긴 함.

다음부터는 댓글 말고 이슈 새로 만들어주셈. 이러면 확인이 제대로 안 되니까

**Comment by Hoto-Mocha** [comment]
녹픽던에서 수정된 거일 수도 있어서 일단 이 이슈는 닫아 두겠음. 다음에 버그가 또 발생하면 조건을 알려 주길 바람.
