### ISSUE TITLE
Game crashes when using a kitchen knife on a statue

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#179]
## 필수 정보
- 게임의 버전(Ex.1.28.1) : 2.9.0
- [No] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요?
- [Yes] 게임에 크래시가 발생했나요(튕겼나요)?
- 버그 내용 : game crashes
- 버그 발생 조건 : The game will crash when the statue hits the player with a kitchen knife.

**Comment by Hoto-Mocha** [comment]
Fixed in 2.10.0. Thanks for reporting!
