### ISSUE TITLE
A bug that revives the final boss

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#183]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.10.1
- [no] Was your save created from previous version?
- [no] Did a crash occurs with the game?
- About The Bug :This bug has been around since the Layer 6 update, but I've only recently identified its Triggering conditions.
- Bug Occurrence Conditions : When a save has defeated the final boss and completely closed the game and restarted (regardless of whether the game was saved or not), the final boss will be revived when entering the save again.

## Optional Infomations
- Screenshot :

**Comment by Hoto-Mocha** [comment]
fixed in 2.10.2. Thanks!
