### ISSUE TITLE
You removed a language option right?

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#189]
I am a Chinese player.
Can you tell me why?

**Comment by Hoto-Mocha** [comment]
Maybe there's some mistake while fetching upstream, chinese language occured some error, so I removed them. it will soonly be fixed

**Comment by Beyond121** [comment]
My friends and I love this game, and I'm making and testing translated texts in Chinese, but this update we found that the Chinese option in the language was removed, which shocked us and worried about why . In fact, it is difficult for us not to have some associations. If there is no particular reason for this result, thank you for the game! Hopefully the Chinese option will be back in the next version!

**Comment by Hoto-Mocha** [comment]
Thanks a lot! It has fixed for now, and will be applied in v2.14.1, the next version.

**Comment by Beyond121** [comment]
Thanks!

**Comment by Hoto-Mocha** [comment]
Released v2.14.1 now, please check the release.

**Comment by Beyond121** [comment]
Alright, thanks!
