### ISSUE TITLE
연소 이펙트 안 보임

### ISSUE THREAD

**Issue by atmosquito** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#193]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.28.1) : 2.14.1
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? 아니요
- [ ] 게임에 크래시가 발생했나요(튕겼나요)? 아니요
- 버그 내용 : 캐릭 위에 연소 이펙트가 안 보임요. 간수한테 화염막대를 썼는데 간수가 그쪽으로 끌었음. 가자마자 인벤열고 물약 깰려고 던지기 버튼까지 눌렀는데! 이펙트가 안 보이는거임ㄷㄷ
- 버그 발생 조건 : 화염막대가 문제이거나 간수가 문제일거같은데 정확한건 모르겠음

## 선택 정보
- 스크린샷 첨부
![Screenshot_20220423-154416](https://user-images.githubusercontent.com/103940152/164883584-25558330-370f-4081-8b49-da4fc2262215.jpg)
![Screenshot_20220423-154433](https://user-images.githubusercontent.com/103940152/164883589-3bacb901-0fc3-402e-8bad-33ef3eeaaa56.jpg)

**Comment by Hoto-Mocha** [comment]
이건 동시에 일어나는 거에서 발생하는 일시적인 오류인 것 같은데. 아마 메인화면 갔다 오면 바로 수정될 거임. 이건 녹픽문제일 가능성이 큼

**Comment by Hoto-Mocha** [comment]
게임에 크게 영향을 주는 건 아니니 일단 해결된 것으로 간주하고 이슈는 닫아 두겠음
