### ISSUE TITLE
Scroll of Enchantment crashes the game

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#194]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.14.1
- [ ] Was your save created from previous version?
- [x] Did a crash occurs with the game?
- About The Bug : The game crashes when you use an Scroll of Enchantment and click outside the backpack panel while selecting.
- Doing this in ShatteredPD doesn't crash.

**Comment by Hoto-Mocha** [comment]
Fixed in v2.15.0.
