### ISSUE TITLE
A bug that made the game unplayable

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#202]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.16.0
- [ ] Was your save created from previous version?
- [ ] Did a crash occurs with the game?
- About The Bug : This bug was discovered by a friend of mine, and I haven't tested it, so I can't fully guarantee its authenticity.
- Bug Occurrence Conditions : When 포트리스's counterattack is blocked by Dwarf Monk, the round cannot end.

**Comment by Hoto-Mocha** [comment]
Fixed in 2.17.0.
