### ISSUE TITLE
의사 튕김 버그

### ISSUE THREAD

**Issue by atmosquito** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#206]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.28.1) : 2.17.0
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요?
- [x] 게임에 크래시가 발생했나요(튕겼나요)?
- 버그 내용 : 공격이 빗나가서 의사 스택은 초기화됐는데 3-5특은 초기화 안 됨. 버튼 그대로 남아있음. 그 상태에서 사용하거나 그 상태로 게임을 재접하려하면 튕김
- 버그 발생 조건 : 버튼 연타하면서 씹히는걸?수도있음

## 선택 정보
- 스크린샷 첨부

**Comment by Hoto-Mocha** [comment]
v2.19.0에서 수정 완료
