### ISSUE TITLE
포트리스 반격 튕김버그

### ISSUE THREAD

**Issue by NoJamCHAN** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#209]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.28.1) : 2.16.1
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? X
- [ ] 게임에 크래시가 발생했나요(튕겼나요)? O
- 버그 내용 : 포트리스 반격중 무한루프
- 버그 발생 조건 : 적 두 명을 상대로 가드를 올리고 공격을 연타하다보니 게임이 멈췄습니다. 왼쪽 위 턴 인디케이터가 한무로 돌고 있어서 무한루프라고 생각했습니다.
플레이 중 두 번 발생했는데 첫 번째는 메인메뉴 갔다오니 해결됐고, 두 번째는 메인메뉴 나와서 계속하기를 누르면 바로 게임이 튕깁니다. 둘 다 19층이었고 두 경우 다 수도승이 있었던 것 같습니다. 수도승 반격시 튕김...?

## 선택 정보
- 스크린샷 첨부

**Comment by Hoto-Mocha** [comment]
v2.17.0 이상 버전으로 업데이트 하면 해결됨.
