### ISSUE TITLE
There is something wrong with the challenge "Superman"

### ISSUE THREAD

**Issue by RZ-IN** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#214]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.21.0
- [No] Was your save created from previous version?
- [No] Did a crash occurs with the game?
- About The Bug : 

The damage caused by hero's wands will be still "1x" multiplier when the challenge "superman" is selected.Could you please check it?XD

- Bug Occurrence Conditions : 

Unconditional.

## Optional Infomations
- Screenshot :

I can't upload screenshot. But the original text is "ALL damage dealt by hero will be multiplied by 3x".

**Comment by Beyond121** [comment]
In the challenge "Pyromaniac", the attack of the hero's wands will not set the target on fire.

**Comment by Hoto-Mocha** [comment]
the damage multiplier affects only physical damage. so it's not a bug

**Comment by Hoto-Mocha** [comment]
I will add a description in the superman challenge's info. 'All physical damage dealt ~' Thanks!
