### ISSUE TITLE
연금술의 주문서도 마법융합으로 연금?

### ISSUE THREAD

**Issue by glasslim** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#215]
## 이슈 작성 전 참고사항
1. 아이디어 제안은 게임에 맞지 않는다고 판단되거나 코딩 실력의 한계로 구현이 불가능한 경우 답변 없이 이슈가 닫힐 수 있음을 알려드립니다.
2. 챌린지 관련 아이디어는 받지 않습니다.

## 아이디어 제보(자유롭게 적어 주시면 됩니다.)

강줌처럼 연금술의 주문서로도 마법부여 유지한채로 강화할 수 있는 조합법이 필요하다 생각함

**Comment by Hoto-Mocha** [comment]
밸런스 상 다음 선택지 중 하나를 선택하면 됨

1. 연금술의 주문서로 만드는 마법 융합 레시피를 추가하는 대신 분해의 주문서 제작 레시피 삭제

2. 연금술의 주문서로 만드는 마법 융합 레시피를 추가하는 대신 분해의 주문서 사용 시 강화수치 일부 손실

3. 현재 상태 그대로 유지

**Comment by Hoto-Mocha** [comment]
3번으로 간주하고 이슈는 닫아 두겠음. 생각이 바뀌면 다시 이슈 작성 바람
