### ISSUE TITLE
Farming at 4f with gambler challenge

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#221]
Will it still be legal in future updates?

I won 11 challenges by doing this.

https://user-images.githubusercontent.com/16593263/172508135-07f38c3b-2907-4dd9-88a7-a6abe098499b.mp4

**Comment by Hoto-Mocha** [comment]
I don't think there is a problem because activating that challenge also proves the measure of your skills.

**Comment by Hoto-Mocha** [comment]
This is also because as long as it is showen to turn on that challenge, all players can know the difficulty of that run at the time.
