### ISSUE TITLE
2.23.0~2.24.1 내내 추출의 주문서가 나오지 않음

### ISSUE THREAD

**Issue by IAMAMAN1** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#228]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.28.1) : 2.23.0~2.24.1 (추출의 주문서로 변경된 후 ~ 지금까지)
- [ X ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요?
- [ X ] 게임에 크래시가 발생했나요(튕겼나요)?
- 버그 내용 : 추출의 주문서가 3~5계층 중 무조건 하나가 발생하도록 되었다고 했는데, 지금까지 추출의 주문서를 본 적이 없음. 3계층에서 계속 마법 지도, 청명, 마법 시야 등등 다 써 가면서 확인해봤는데도 없었음.
- + 이건 운이 나빠서인건진 몰라도 분해의 주문서도 처음 나온 이후 삭제될 때까지 나온 적 없었음
- 버그 발생 조건 : 알 수 없음

## 선택 정보
- 스크린샷 첨부

**Comment by Hoto-Mocha** [comment]
어... 안 그래도 그거 고치려고 확인해 봤는데, 코드 자체를 드랍률 50%로 만들어 놓고 업데이트 내역에 반드시 나온다고 적어 놨었네.
![image](https://user-images.githubusercontent.com/76470428/176947347-712e584a-b2c6-402d-8b83-3916903b472c.png)
우선 고치려고 예정한 바는 그대로 진행할 예정이고, 보조 무기와 같은 방식, 즉 2~4계층에 반드시 출현하게 만들 생각임.

**Comment by IAMAMAN1** [comment]
그냥 50%를 5연속으로 못 맞춘 거였구나... 2~4계층 확정이면 19층에 나오는 게 아닌 이상 연금무기 편하게 플랜 짜서 갈 수 있겠다
