### ISSUE TITLE
Scroll of Extraction can be used on special weapons

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#231]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.25.0
- [ ] Was your save created from previous version?
- [ ] Did a crash occurs with the game?
- About The Bug : You can use Scroll of Extraction for the weapons of similar SLEEP GUN and will not lose the level.

## Optional Infomations
- Screenshot :

**Comment by betacon** [comment]
same here, seems only sleep gun and it's upgrade versions have this bug

**Comment by Hoto-Mocha** [comment]
fixed in v2.26.0.
