### ISSUE TITLE
Scimitar of lightning cannot be identified by using it

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#232]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.25.0
- [ ] Was your save created from previous version? No
- [ ] Did a crash occurs with the game? No
- About The Bug :  I can't remember how many times it is used, but I cleared floor 16~20 with it, yet still be unidentified.

**Comment by Hoto-Mocha** [comment]
fixed in v2.26.0.
