### ISSUE TITLE
Potion preserve works on elixir of talent

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#233]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.2.25.0 
- [ ] Was your save created from previous version? No
- [ ] Did a crash occurs with the game?
- About The Bug : No
- Bug Occurrence Conditions : Researcher tier3 talent says it won't work on potion of strength and potions based on POS

## Optional Infomations
- Screenshot :![Screenshot_20220707-044520.jpg](https://user-images.githubusercontent.com/16593263/177640777-f6b4e6dc-bb6c-479c-849e-dcf4f004509e.jpg)

**Comment by Hoto-Mocha** [comment]
fixed in v2.26.0.
