### ISSUE TITLE
The Unreasonableness of Scroll of Transmutation

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#234]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.25.0
- [ ] Was your save created from previous version?
- [ ] Did a crash occurs with the game?
- About The Bug : Using Scroll of Transmutation on a Tier 5 weapon may turn into a Remote Explosion Control Device. This problem has always existed.

## Optional Infomations
- Screenshot :
![Screenshot_2022-07-07-20-23-29-61](https://user-images.githubusercontent.com/103019447/177774254-cdca73f4-ed88-4af8-a786-74be62b2f943.jpg)

**Comment by Hoto-Mocha** [comment]
applied in v2.26.0.
