### ISSUE TITLE
ranking challenges displaying bug

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#235]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.26.0
- [ ] Was your save created from previous version?
- [ ] Did a crash occurs with the game?
- About The Bug : 
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :![Screenshot_20220709-163816.jpg](https://user-images.githubusercontent.com/16593263/178098874-b55dcb98-9782-4d93-84c9-4d4fc93e2c20.jpg)

**Comment by Hoto-Mocha** [comment]
fixed in v2.26.1.
