### ISSUE TITLE
Game crashes while ascending to floor 30

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#237]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.26
- [ ] Was your save created from previous version?no
- [ ] Did a crash occurs with the game?yes
- About The Bug : 
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :https://user-images.githubusercontent.com/16593263/178119208-04df3d62-a337-4624-a3dd-b8b816795e9f.mp4

**Comment by Hoto-Mocha** [comment]
fixed in v2.26.1. Please fill out the details next time.
