### ISSUE TITLE
Jack of all trades badge doesn't  count after 2.26 to 2.26.1 patch

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#239]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.26.1
- [ ] Was your save created from previous version? yes
- [ ] Did a crash occurs with the game? no
- About The Bug : I used the 2.26 save file after floor 30 crashing bug was fixed, and it doesn't count as defeating the 3rd boss.
- Bug Occurrence Conditions : The veteran word didn't  turn yellow.

## Optional Infomations
- Screenshot :https://user-images.githubusercontent.com/16593263/178152604-131417c0-56ee-45a1-817e-1e52599afc88.mp4

**Comment by Hoto-Mocha** [comment]
Actually, ARPD does not trigger boss-related badges because of my limitation of coding. I'll try taking care of it, but I cannot guarantee it will be fixed.

**Comment by betacon** [comment]
seems that take the amulet of yendor to the ground doesn't count, you have to obtain it at floor 30 and end the game.

**Comment by betacon** [comment]
Master of many trade badge seems to be not working on mages too

**Comment by betacon** [comment]
> Actually, ARPD does not trigger boss-related badges because of my limitation of coding. I'll try taking care of it, but I cannot guarantee it will be fixed.

new sub-classes of the original 4 such as veteran, engineer won't count as defeating DM300

**Comment by betacon** [comment]
> > Actually, ARPD does not trigger boss-related badges because of my limitation of coding. I'll try taking care of it, but I cannot guarantee it will be fixed.
> 
> new sub-classes of the original 4 such as veteran, engineer won't count as defeating DM300

WAIT, You only need to defeat DM300 with the original 8 classes...that's definitely a bug.

**Comment by Hoto-Mocha** [comment]
fixed in v2.27.0, but it need to check if it works well.

**Comment by Hoto-Mocha** [comment]
I will consider this issue resolved and close this issue. If there is a new problem, please rewrite the issue.
