### ISSUE TITLE
Scroll of extraction can be used on old wand and won't lose levels

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#240]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.26
- [ ] Was your save created from previous version? no
- [ ] Did a crash occurs with the game? no
- About The Bug : as title
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :![Screenshot_20220711-042932.jpg](https://user-images.githubusercontent.com/16593263/178161205-6867543d-d44b-4ede-bf38-bb8d08729b0d.jpg)

**Comment by Hoto-Mocha** [comment]
I can't understand your sentence.

**Comment by Hoto-Mocha** [comment]
I need the information of what is the 'old wand', and what did you do, things like that. So I ask you to write down the report in detail, please.

**Comment by betacon** [comment]
I mean the magician's original staff, you can just extract 3 scrolls from it and it will stay level 3

**Comment by Hoto-Mocha** [comment]
fixed in v2.27.0.
