### ISSUE TITLE
Scroll of alchemy  cannot be used on anti-tank rocket

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#241]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.26.1
- [ ] Was your save created from previous version? no
- [ ] Did a crash occurs with the game? no
- About The Bug : as title
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot : https://user-images.githubusercontent.com/16593263/178165956-13d8ea53-0411-4c86-a193-306b343f3613.mp4

**Comment by Hoto-Mocha** [comment]
Anti-Tank Rocket is not a weapon FROM ALCHEMY POT.
