### ISSUE TITLE
Modifications from Stone of Augmentation are preserved when weapons become guns

### ISSUE THREAD

**Issue by Beyond121** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#242]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.26.1
- [ ] Was your save created from previous version?
- [ ] Did a crash occurs with the game?
- About The Bug : Using Scroll of Transmutation on a weapon that has used Stone of Augmentation will retain the modification even if the weapon is turned into a gun.

## Optional Infomations
- Screenshot :
![Screenshot_2022-07-13-11-24-17-39](https://user-images.githubusercontent.com/103019447/178644454-ec3d3372-bb6a-4fda-9c39-39acd7cf9bfe.jpg)

**Comment by Hoto-Mocha** [comment]
Actually it's not a bug, thanks for reporting.
