### ISSUE TITLE
Game crashed while trying to transmute lance and shield

### ISSUE THREAD

**Issue by betacon** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#244]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.261
- [ ] Was your save created from previous version? no
- [ ] Did a crash occurs with the game? yes
- About The Bug : as title 
- Bug Occurrence Conditions : dunno

## Optional Infomations
- Screenshot : https://user-images.githubusercontent.com/16593263/179380788-9145485f-cb34-49b8-ab40-3955bcdb98a3.mp4

**Comment by Hoto-Mocha** [comment]
fixed in v2.27.0.
