### ISSUE TITLE
숲지기 부활 후 튕김

### ISSUE THREAD

**Issue by ahls** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#251]
숲지기 드워프 광산 들어와서 일반앙크로 부활했습니다.
부활템은 3강 쇠뇌(마법 없음, 녹픽던 쇠뇌)와 2강된 활(궁수 기본템)을 선택하고 한발자국 움직이니까 튕겼어요.
그 이후로는 그 캐릭터를 로딩하면 바로 튕깁니다.
감삼다

**Comment by ahls** [comment]
레이블 어케 넣는지 몰겟어용.. 죄송함다

**Comment by Hoto-Mocha** [comment]
이슈 작성 시 버그 제보 템플릿이 있으니 그쪽으로 다시 작성 부탁드립니다.
