### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by joint001** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#259]
![Screenshot_20220920_024950_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/106447327/191093138-7ef8ed1c-4f5c-4dcd-b0e9-f04ffb66982c.jpg)
## Essential Infomations
- Version of the game(Ex.2.32.0) : 
- [ ] Was your save created from previous version?
- [ ] Did a crash occurs with the game?
- About The Bug : When I use the holy sword to attack the enemy，I'm stuck，I can't do anything
![Screenshot_20220920_024950_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/106447327/191093109-339ca95f-b4ed-4d94-9113-9337ecb1e5a3.jpg)

- Bug Occurrence Conditions : Use the holy sword to attack the enemy when the strength is not enough

## Optional Infomations
- Screenshot :

**Comment by Hoto-Mocha** [comment]
It's not a bug. It's just using tons of time, because of lack of strength.
