### ISSUE TITLE
착용무기 사라짐 버그

### ISSUE THREAD

**Issue by ekdnsfhem** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#261]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 명확한 버그 발생 조건이 없으면 답변이 불가합니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.
7. 크래시 로그는 크래시 버그 수정에 사용할 수 있는 강력한 도구가 됩니다. 크래시 발생 시 가능하다면 크래시 로그도 첨부하여 주시기 바랍니다. [모바일 로그캣 만드는 방법](https://055055.tistory.com/8)

## 필수 정보
- 게임의 버전(Ex.2.28.0) : 2.31.0
- 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? : 아니오
- 게임에 크래시가 발생했나요(튕겼나요)? : 아니오
- 버그 내용(문제가 어떻게 발생하는지) : 착용하고 있는 무기 (강화도 가능하고 저주강화도 가능, 실제 성능 발휘 가능)가 다른 무기 장착시 사라짐.
- 
- 버그 발생 조건(무엇을 해야 해당 문제를 발생시킬 수 있는지) : 

1. 사무라이로 특대검 착용한 상태에서 빛의 특대검 만듦.

2. 무기칸에 껴져있는거 특대검 모양인것만 보고 이름은 확인 안하고 강줌 9장 바름

3. 추출줌서로 뽑아낸 연금강화서 바르려고 하니 착용중이던 9강 특대검에 안발림

4. 뭐지 하면서 일반강줌 1장을 더 발라서 10강 특대검으로 만듬.

5. 확인해보니 빛의 특대검은 인벤에 있었고 손에는 그냥 특대검이 들려있음. 그냥 특대검에 10강 바른거임..

6. 좌절하면서 빛의 특대검 껴보기나 해보자 하고 빛의 특대검 착용함.

6. 원래 착용중이던 10강 특대검이 사라짐.

7. 인벤에도 없고 바닥에도 없음..

8. 혹시 몰라 빛의 특대검 착용해제해봤는데 사라진 10강 특대검이 생겨나지는 않음..

* 특성은 스샷으로 올리겠음.
* 연금술 솥에서 한칸떨어진 자리에서 움직이지 않았음.

## 선택 정보
- 스크린샷 첨부
![Screenshot_20220922-112650](https://user-images.githubusercontent.com/67538283/191645261-ddd4bd42-984d-45e3-8070-c863a962d171.png)
![Screenshot_20220921-221411](https://user-images.githubusercontent.com/67538283/191645285-c83f0e37-d3f5-44d7-bf8a-626d39b413b8.png)

- (PC) 크래시 로그(사진) : 
- (모바일) 크래시 직후 생성한 로그캣(파일) : 
- 버그 발생 후 계속 진행해서 역행하다가 죽은 상태라 현 상황에서는 도움이 안될것 같습니다. 필요하시면 방법 찾아서 올리겠습니다.
-

**Comment by Hoto-Mocha** [comment]
해당 버그 때문에 착용 중인 장비는 연금술 재료로 사용할 수 없도록 만들어 놨었는데, 그 쪽에 무슨 문제가 생긴듯.

**Comment by Hoto-Mocha** [comment]
v1.4.0에서 수정함. 근본적인 원인은 해결을 못 했지만 그냥 퀵레시피를 사용하지 못 하도록 수정했음
