### ISSUE TITLE
treasure hunter's shovel can't trigger

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#263]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 
- [ no ] Was your save created from previous version?
- [ no ] Did a crash occurs with the game?
- About The Bug : When treasure hunter kills the enemy with a shovel, there's no obtain additional trophies.
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :

**Comment by Hoto-Mocha** [comment]
There's missing essential information. Please write issue again in detail.
