### ISSUE TITLE
Treasure Hunter will not drop extra items when killing enemies with a shovel

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#266]
## Essential Infomations
- Version of the game(Ex.2.33.0) : 
- [ no] Was your save created from previous version?
- [ no] Did a crash occurs with the game?
- About The Bug : Treasure Hunter will not drop extra items when killing enemies with a shovel
- Bug Occurrence Conditions : I use shovel to kill about 10 monsters, but unlike wealth rings or fortune enchantments, it can't drop additional items, and I have upgraded the skill

## Optional Infomations
- Screenshot :
![Screenshot_20221018_080917_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/196309657-63ad0001-279c-4d8e-8413-98504575681b.jpg)

**Comment by Hoto-Mocha** [comment]
fixed in 2.34.0.
