### ISSUE TITLE
인터페이스 버그 및 오타 제보

### ISSUE THREAD

**Issue by gwak1635** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#267]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 명확한 버그 발생 조건이 없으면 답변이 불가합니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.
7. 크래시 로그는 크래시 버그 수정에 사용할 수 있는 강력한 도구가 됩니다. 크래시 발생 시 가능하다면 크래시 로그도 첨부하여 주시기 바랍니다. [모바일 로그캣 만드는 방법](https://055055.tistory.com/8)

## 필수 정보
- 게임의 버전(Ex.2.28.0) : 2.33.0
- 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? : no
- 게임에 크래시가 발생했나요(튕겼나요)? : no
- 버그 내용(문제가 어떻게 발생하는지) :  오타 발생(특청 위치)및 글자가 안 보임
- 버그 발생 조건(무엇을 해야 해당 문제를 발생시킬 수 있는지) :  맨 처음 게임을 시작할 때 혹은 상시

## 선택 정보
- 스크린샷 첨부
- (PC) 크래시 로그(사진) : 
![Screenshot_20221018-183702](https://user-images.githubusercontent.com/29707410/196395416-62445888-3ca8-44ff-af7d-4a35adb2c97d.png)

- (모바일) 크래시 직후 생성한 로그캣(파일) :

**Comment by Hoto-Mocha** [comment]
오타가 어디에 있다는 건지 명시해 주길 바람.

**Comment by Hoto-Mocha** [comment]
2.34.0에서 수정완료
