### ISSUE TITLE
Swordmaster use  semi-automatic pistol to attack increase combo value bug

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#269]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.34.0
- [no ] Was your save created from previous version?
- [ no] Did a crash occurs with the game?
- About The Bug : The combo has been cleared. Shooting the enemy with the semi-automatic pistol combo mode will make the combo hit value reach the maximum
- Bug Occurrence Conditions : 
3-1 + 3, 3-5 + 1. When the combo point is cleared, use the semi-automatic pistol combo mode to hit the enemy, and the combo point becomes 7
PS：3-5 +2，Combo value 7，when I stow the knife, I critically attack the enemy ，temporary grade +1，combo value 3，temporary grade +2
PS：shattered PD already upgrade to 1.4.2 

## Optional Infomations
- Screenshot :
![Screenshot_20221028_144521_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/198834375-6d4986af-8dcb-4397-9ffb-b834964891a9.jpg)
![Screenshot_20221028_144531_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/198834379-f5cdc1f1-f165-48ac-8429-6b28a3a292dc.jpg)
![Screenshot_20221028_144537_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/198834387-75b1ee00-5d51-4a9b-bd6a-16518ff84048.jpg)
![Screenshot_20221028_144547_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/198834393-74b8ac82-4533-404a-b1d8-f196cfd0744e.jpg)
![Screenshot_20221028_144555_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/198834401-6dc1e139-933d-41e7-b4c0-17c792320724.jpg)

**Comment by Hoto-Mocha** [comment]
Fixed in v2.35.0.
