### ISSUE TITLE
Ghost equipment carbine can't fire ghost bullets, it can only be used as a melee weapon

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#271]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 2.34.0
- [no ] Was your save created from previous version?
- [no ] Did a crash occurs with the game?
- About The Bug : Ghost equipment carbine can't fire ghost bullets, it can only be used as a melee weapon
- Bug Occurrence Conditions : 
Ghost equipped pistols can fire ghost bullets, but equip carbines can't
## Optional Infomations
- Screenshot :
![Screenshot_20221031_233107_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/199048315-05060cc9-48fe-42ee-b5a3-c6119461705e.jpg)
![Screenshot_20221031_233239_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/199048328-0d72ba4e-242d-4059-bc8b-0462cecb80d6.jpg)
![Screenshot_20221031_233342_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/199048340-3cb6a5ff-5901-4ba1-8711-6ca53c309c94.jpg)
![Screenshot_20221031_233351_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/199048348-ffae5dc3-8601-4037-8d18-decb9b105ed9.jpg)
![Screenshot_20221031_233404_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/199048360-3f317e4e-e589-4fbc-8b52-aa1381745dd5.jpg)

**Comment by Hoto-Mocha** [comment]
Fixed in v2.35.0.
