### ISSUE TITLE
활 고급진화 인챈 날아가는 문제 문의합니다

### ISSUE THREAD

**Issue by thunderwhale3012** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#272]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 명확한 버그 발생 조건이 없으면 답변이 불가합니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.
7. 크래시 로그는 크래시 버그 수정에 사용할 수 있는 강력한 도구가 됩니다. 크래시 발생 시 가능하다면 크래시 로그도 첨부하여 주시기 바랍니다. [모바일 로그캣 만드는 방법](https://055055.tistory.com/8)

## 필수 정보
- 게임의 버전(Ex.2.28.0) : 2.34.0
- 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? : 현 버전 세이브입니다
- 게임에 크래시가 발생했나요(튕겼나요)? : NO
- 버그 내용(문제가 어떻게 발생하는지) : 활 고급진화 했을 때 미식별 상태가 되어있으며, 인챈이 유지되지 않습니다.
제 기억이 맞다면 녹픽 1.4.0을 갖고 오기 전 버전에서는 고급진화 후에도 식별상태였고, 인챈도 유지되었습니다.
본 내용이 의도적인 변경인지 아니면 버그인지 알려주셨으면 합니다. 패치노트에서는 못 본 거 같습니다.

## 선택 정보
- 스크린샷 첨부
![1667351857](https://user-images.githubusercontent.com/76144132/199395519-e8d29f5d-ef8f-40e3-9d5d-b327f9709d10.jpg)

![1667351857 (1)](https://user-images.githubusercontent.com/76144132/199395531-ecf520b6-99b2-43fa-b1d1-507d9148ab97.jpg)
![1667351862](https://user-images.githubusercontent.com/76144132/199395537-75dce803-c94d-4ecf-84e8-90815b3f64bc.jpg)

**Comment by thunderwhale3012** [comment]
스샷 부가설명 : 
1. 고급 진화하기 전 활에는 진한 적색의 흡혈 인챈이 붙어있었습니다.
2. 고급진화 후에, 활이 미식별 상태가 되었습니다.
3. 활을 식별하고 살펴보니, 활에 인챈이 사라져있었습니다. 강화치는 유지되어있습니다.

**Comment by Hoto-Mocha** [comment]
의도하지 않은 사항이고, 원인 파악 및 수정이 계획에 있음.

**Comment by Hoto-Mocha** [comment]
v2.35.0에서 수정완료
