### ISSUE TITLE
공지사항

### ISSUE THREAD

**Issue by Hoto-Mocha** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#274]
개발자(본인)가 스팀에서 60만원 사기를 당해서 심리 상태가 매우 좋지 않습니다.
현재 경찰 접수는 했지만 추가적인 증거물 제출을 위해 한번 더 방문해야 하는 상황이고, 스팀 계정은 되찾아서 그나마 좀 나은 상태입니다.
따라서 당분간은 개발 과정에 착수하기 어려울 것 같습니다.
총픽던을 재미있게 즐겨 주시고 업데이트를 기대해 주신 분들께 실망감을 안겨 드린 것 같아서 마음이 무겁습니다.
버그 및 아이디어 제보는 받고 있으니 해당사항이 있다면 제보 바랍니다.
감사합니다.

**Comment by sjsxmd** [comment]
I feel sorry for what happened to you. I think this game is very good. If the developers have financial problems, it's better to set up a donation way.
