### ISSUE TITLE
보우건을 몹이 아닌 벽이나 바닥에 쏘면 튕기는 버그

### ISSUE THREAD

**Issue by thunderwhale3012** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#275]
# 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈 **(특히 개발자가 작성한 '수정사항' 이슈)** 가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 명확한 버그 발생 조건이 없으면 답변이 불가합니다.
4. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
5. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
6. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.
7. 크래시 로그는 크래시 버그 수정에 사용할 수 있는 강력한 도구가 됩니다. 크래시 발생 시 가능하다면 크래시 로그도 첨부하여 주시기 바랍니다. [모바일 로그캣 만드는 방법](https://055055.tistory.com/8)

##
- 게임의 버전(Ex.2.28.0) : 2.34.0
- 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? : - (하단 참고)
- 게임에 크래시가 발생했나요(튕겼나요)? : Y
- 버그 내용(문제가 어떻게 발생하는지) : 
녹픽갤에 여러번 올라온 내용인데, 아무도 여기에 안 올리길래 대신 올립니다. 
(직접 테스트한 내용이 아니지만 툭하면 보이는 내용이라, 실제 버그로 추정하여 올립니다)
버전은 각 스샷에 있는 버전입니다, 중간에 업뎃 없이 진행되었을 것으로 추측됩니다.
https://gall.dcinside.com/mgallery/board/view/?id=spd&no=43362
https://gall.dcinside.com/mgallery/board/view/?id=spd&no=42438
https://gall.dcinside.com/mgallery/board/view/?id=spd&no=42652
이외에 스샷 없이 튕겼다고 적은 글도 두 건 정도 있었는데, 스샷 없어 따로 기재하지 않았습니다.
보우건을 몹이 아닌 벽이나 바닥에 쏘면 튕기는 버그라고 합니다.
튕긴 뒤에 다시 해당 캐릭터 선택하면 층 처음부터 시작한다고 하네요.
- 버그 발생 조건(무엇을 해야 해당 문제를 발생시킬 수 있는지) : 

## 선택 정보
- 스크린샷 첨부
- (PC) 크래시 로그(사진) : 
- (모바일) 크래시 직후 생성한 로그캣(파일) :

**Comment by Hoto-Mocha** [comment]
v2.35.0에서 수정완료
