### ISSUE TITLE
About some problems in code

### ISSUE THREAD

**Issue by 1015561267** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#276]
##Here by developer from China.My desktop memory is too poor to handle more than one project develop environment at a time so I just analyze your code with experience.Here are some little issues:

##Talent LETHAL_RAGE have problem,Berserk buff releated.
File Locate:https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/buffs/Berserk.java
![image](https://user-images.githubusercontent.com/52144800/201481858-7f74f805-8276-4c72-aa66-fc30eeee659d.png)
Here,you have that maxpower 1,1.1,1.2,1.3 each level by ENDLESS_RAGE,different from what works when taking damage.
![image](https://user-images.githubusercontent.com/52144800/201482052-71cd086b-0c8a-45d5-977a-48f857ade1d8.png)
And I assume you don't know berserk can be triggered manually in SPD 1.4 update,so you should make the active skill icon available when gain range by kill too.(If what functions now is not what you pretend to)

##Talent SKILL_ENHANCE have problem,Combo buff releated.
File Locate:https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/buffs/Combo.java
Wrong math calculation order cause two combo skills wrongly function.
![image](https://user-images.githubusercontent.com/52144800/201482422-4cc26c51-126b-4205-91d2-bb5aaf80752c.png)
Here,the function of SLAM should be:
				dmgBonus = Math.round( target.drRoll() * ( count + hero.pointsInTalent(Talent.SKILL_ENHANCE) ) / 5f );
and the funcion of CRUSH should be:
				dmgMulti = 0.25f * ( count + hero.pointsInTalent(Talent.SKILL_ENHANCE) );

##Problem in file management and Hero.java
Your directory in https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/tree/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee is too large as more than 160 files while evan only have less than 30 there.Guns themself,along with other weapons,should use tag to distinguish instead,otherwise it could only be a burden when adding even more weapons.AP/HP should be a value like you did inGunSmithingTool,affect damage,function and info accordingly.Same reason when it comes to MagicBook and MagicSword.

##Last but not least
Just to tell you that there are a great pile of chinese are playing ARranged Pixel Dungeon,feel fun and have happy time in because of it.So all of them feel bad when heard about that bad news,hope you can overcome it,and looking forward to get new version with exciting things.
Well,as to myself,as long as one continues on his road,he is not done yet.I have faith in you.

**Comment by Hoto-Mocha** [comment]
Fixed in v2.35.0 about talents, and about codes, I postponed to fix it because of lack of my coding skill. I tried to fix and manage it, but I failed and was discouraged by this problem and didn't do coding itself for a while. I hope you can understand this.
