### ISSUE TITLE
skip turn too fast on botanist

### ISSUE THREAD

**Issue by Netherso** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#284]
## Essential Infomations
- Version of the game(Ex.2.26.0) : 
- [ ] Was your save created from previous version?
-  No
- [ ] Did a crash occurs with the game?
-  No
- About The Bug : 
-
![Screenshot_20221213_190212_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/85202461/207302860-152e8a0a-fb8f-4afd-bfbd-2460b95cc594.jpg)
![Screenshot_20221213_190159_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/85202461/207302887-d19c557d-9ada-460a-8515-4def62357bd6.jpg)
it's skip turns fast when use the "botanist" to click the grass
- Bug Occurrence Conditions : 
 use "botanist",click grass
## Optional Infomations
- Screenshot :

**Comment by Hoto-Mocha** [comment]
check the latest version.
