### ISSUE TITLE
SFX disappear when use old music

### ISSUE THREAD

**Issue by Netherso** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#285]
## Essential Infomations
- Version of the game(Ex.2.36.0) : 
- [ ] Was your save created from previous version?
-No
- [ ] Did a crash occurs with the game?
-No
- About The Bug : 
-when I turn on use old music,game will lost SFX.
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :
![Screenshot_20221216_002135_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/85202461/207914698-6bf365b5-7f7d-4057-bfaf-60d5999c5e59.jpg)

**Comment by Hoto-Mocha** [comment]
It needs restarting gsme or re-setting SFX.
The sentence that explains this have existed before, but it was removed because of lack of space of button.
