### ISSUE TITLE
打到29層後就打不開是怎麼回事？？

### ISSUE THREAD

**Issue by iseli-isameinro** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#286]
## Essential Infomations
- Version of the game(Ex.2.10.0) : 
- [ ] Was your save created from previous version?
- [x] Did a crash occurs with the game?
- About The Bug : 
- After go downstairs in 29 , I couldn't open the dete. Up date in new , battery power, clear device memory couldn't useful.
- My phone is Galaxy A22  , is CPU over loading???

## Optional Infomations
- Screenshot :
![Screenshot_20221228_162213](https://user-images.githubusercontent.com/121543355/209781707-2e7eb083-1665-4a41-bf54-25b943df44ba.jpg)

**Comment by Hoto-Mocha** [comment]
this need enough information, and use english please.
