### ISSUE TITLE
6단계 무기 진화 시도할 경우 오류

### ISSUE THREAD

**Issue by tommy-gilbut** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#288]
쌍특대검 같은 6단계 조합 무기를 진화 주문서로 진화 시도하면 프로그램이 강제 종료 됩니다.
![Screenshot_20221230-222152](https://user-images.githubusercontent.com/48462034/210074626-9c6c4e14-9a43-41f4-8234-3fe2787961bf.jpg)

**Comment by Hoto-Mocha** [comment]
v2.37.0에서 수정완료
