### ISSUE TITLE
slug-tactical shotgun can't surprise attack

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#300]
## Essential Infomations(Use English Please)
- Version of the game(Ex.2.41.0) : 2.44.0
- [no ] Was your save created from previous version?
- [no ] Did a crash occurs with the game?
- About The Bug : 
- Bug Occurrence Conditions : 
slug-tactical shotgun can't surprise attack,please check
## Optional Infomations
- Screenshot :
![Screenshot_20230128_071144_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/215223524-8dc33b66-1e58-4394-b450-5b6a4578b0a2.jpg)

**Comment by Hoto-Mocha** [comment]
fixed in v2.45.0. thanks
