### ISSUE TITLE
tactical shield

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#302]
## Essential Infomations(Use English Please)
- Version of the game(Ex.2.41.0) : 2.45.0
- [no ] Was your save created from previous version?
- [ no] Did a crash occurs with the game?
- About The Bug : 
- Bug Occurrence Conditions : 
engineer use tactical shield as close weapon can't trigger engineer's talent，please check
## Optional Infomations
- Screenshot :
![Screenshot_20230131_151923_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/215693496-ec7d84b0-8059-4ccd-9687-3c23dd30213b.jpg)
![Screenshot_20230131_151904_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/100021559/215693524-63558601-7fe4-4e07-a0a3-5a1e55cceda5.jpg)

**Comment by Hoto-Mocha** [comment]
Tactical shield is sorted to 'melee weapon', not guns. So it won't trigger the effects of gun-melee-attacking.
