### ISSUE TITLE
paladin bug

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#306]
## Essential Infomations(Use English Please)
- Version of the game(Ex.2.41.0) : 2.46.0
- [ no] Was your save created from previous version?
- [no ] Did a crash occurs with the game?
- About The Bug : When the paladin kills the enemy in the state of blessing, he always turn the enemy into a friendly army. please check
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :

**Comment by Hoto-Mocha** [comment]
fixed in v2.47.0. thanks for letting me know this.
