### ISSUE TITLE
결투자 신규 보조 직업 계획

### ISSUE THREAD

**Issue by Hoto-Mocha** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#316]
- [x] 이름 : 펜서(Fencer)
- [x] 능력 : 무기 충전량을 1 소모하여 최대 2타일을 턴 소모 없이 이동할 수 있음, 이동한 직후 적을 공격하면 공격이 반드시 명중하며 10%의 추가 피해를 입힘
----
특징:
- 특성으로 충전량 소모를 줄일 수 있음
- 특성으로 이동 거리를 늘릴 수 있음
- 특성으로 추가 피해량을 늘릴 수 있음
- 공격 범위가 긴 무기와 잘 어울리는 직업
- 회피탱 컨셉도 가능
----
- [x] 특성
----
- [x] 3-7 : 침착한 발놀림
_+1:_ 대시에 필요한 무기 충전량이 _20%_ 감소합니다.
_+2:_ 대시에 필요한 무기 충전량이 _37%_ 감소합니다.
_+3:_ 대시에 필요한 무기 충전량이 _50%_ 감소합니다.
배율 : 0.795
- [x] 3-8 : 치명적인 가속
_+1:_ 대시 직후 입히는 피해 증가량이 _+6%_ 증가합니다.
_+2:_ 대시 직후 입히는 피해 증가량이 _+11%_ 증가합니다.
_+3:_ 대시 직후 입히는 피해 증가량이 _+17%_ 증가합니다.
배율 : 1.1(기본) * 1.05
- [x] 3-9 : 관성적인 움직임
_+1:_ 대시를 사용한 _직후_ 대시에 소모하는 무기 충전량이 50% 감소합니다.
_+2:_ 대시를 사용한 이후 _1턴_ 동안 대시에 소모하는 무기 충전량이 50% 감소합니다.
_+3:_ 대시를 사용한 이후 _2턴_ 동안 대시에 소모하는 무기 충전량이 50% 감소합니다.
배율 : 0.5
- [x] 3-10 : 공격적인 움직임
_+1:_ 무기 능력을 사용한 직후 대시에 소모하는 무기 충전량이 _50%_ 감소합니다.
_+2:_ +1의 효과에 더불어, 대시를 사용할 때 주변 적들에게 무기 공격력의 _10%의 피해_를 입힙니다.
_+3:_ +2의 효과에 더불어, 대시를 사용할 때 주변 적들에게 _3턴_의 취약을 부여합니다.
- [x] 3-11 : 방해받지 않는 몸놀림
_+1:_ 무기와 방어구의 힘 요구 수치를 초과한 힘 1당 _0.5_의 회피를 얻습니다.
_+2:_ 무기와 방어구의 힘 요구 수치를 초과한 힘 1당 _1_의 회피를 얻습니다.
_+3:_ 무기와 방어구의 힘 요구 수치를 초과한 힘 1당 _1.5_의 회피를 얻습니다.
- [x] 3-12 : 영체화
_+1:_ 대시의 최대 이동 거리가 _1타일 증가_합니다.
_+2:_ +1의 효과에 더불어, 대시가 _적을 관통_합니다.
_+3:_ +2의 효과에 더불어, 대시가 _단단한 타일_을 관통합니다.

**Comment by nupnuts** [comment]
suggest
3-10：
+3：In addition to the +2 effect, Dash adds a 20% Vulnerable Buff to nearby enemies

**Comment by Hoto-Mocha** [comment]
_+1:_ 대시에 필요한 무기 충전량이 _20%_ 감소합니다.\n\n_+2:_ 대시에 필요한 무기 충전량이 _37%_ 감소합니다.\n\n_+3:_ 대시에 필요한 무기 충전량이 _50%_ 감소합니다.


_+1:_ 대시 직후 입히는 피해 증가량이 _+6%_ 증가합니다.\n\n_+2:_ 대시 직후 입히는 피해 증가량이 _+11%_ 증가합니다.\n\n_+3:_ 대시 직후 입히는 피해 증가량이 _+17%_ 증가합니다.


_+1:_ 대시를 사용한 _직후_ 대시에 소모하는 무기 충전량이 50% 감소합니다.\n\n_+2:_ 대시를 사용한 이후 _1턴_ 동안 대시에 소모하는 무기 충전량이 50% 감소합니다.\n\n_+3:_ 대시를 사용한 이후 _2턴_ 동안 대시에 소모하는 무기 충전량이 50% 감소합니다.


_+1:_ 무기 능력을 사용한 직후 대시에 소모하는 무기 충전량이 _50%_ 감소합니다.\n\n_+2:_ +1의 효과에 더불어, 대시를 사용할 때 주변 적들에게 무기 공격력의 _10%의 피해_를 입힙니다.\n\n_+3:_ +2의 효과에 더불어, 대시를 사용할 때 주변 적들에게 _3턴_의 취약을 부여합니다.


_+1:_ 무기와 방어구의 힘 요구 수치를 초과한 힘 1당 _0.5_의 회피를 얻습니다.\n\n_+2:_ 무기와 방어구의 힘 요구 수치를 초과한 힘 1당 _1_의 회피를 얻습니다.\n\n_+3:_ 무기와 방어구의 힘 요구 수치를 초과한 힘 1당 _1.5_의 회피를 얻습니다.


_+1:_ 대시의 최대 이동 거리가 _1타일 증가_합니다.\n\n_+2:_ +1의 효과에 더불어, 대시가 _적을 관통_합니다.\n\n_+3:_ +2의 효과에 더불어, 대시가 _단단한 타일_을 관통합니다.
