### ISSUE TITLE
플레이어가 이동하는 동안 퀵 슬롯과 인벤토리 슬롯이 깜빡거리는데 이것에 의해 눈이 피로할 수 있습니다

### ISSUE THREAD

**Issue by starwindz** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#323]
플레이어가 이동하는 동안 화면 오른쪽 하단의 퀵슬롯 및 인벤토리 슬롯이 잠시 흐리게 표시되었다가 플레이어 이동이 멈추면 원래의 색으로 돌아갑니다. 이것은 일종의 깜박임이며 눈이 피로할 수 있을 것 같습니다. 일반적으로 픽던을 플레이하는데 마우스를 사용하기는 하지만 키보드를 사용하는 플레이어도 많기 때문에 이 깜박거림이 더욱 더 도드라집니다. 

유사한 로그라이크인 돌죽 등도 플레이어가 이동할 때 굳이 유저인터페이스를 disable 상태로 만들지는 않고, 픽던에서 플레이어가 이동하는 동안 사용자 인터페이스에 액세스하는 것이 사실상 불가능하기 때문에, 플레이어가 이동하는 동안 사용자 인터페이스를 굳이 깜박거리게 할 필요는 없어 보입니다. 이에 관련 코드 수정 검토를 요청 드립니다. 감사합니다.

**Comment by Hoto-Mocha** [comment]
활동 중 인터페이스의 비활성화 기능 자체는 SPD 본판의 시스템이라 UI 비활성화 시스템 자체의 제거를 원하시면 SPD 깃허브에 건의하시면 되고, 색깔의 문제라면 수정할 수 있습니다.

**Comment by nupnuts** [comment]
> 플레이어가 이동하는 동안 화면 오른쪽 하단의 퀵슬롯 및 인벤토리 슬롯이 잠시 흐리게 표시되었다가 플레이어 이동이 멈추면 원래의 색으로 돌아갑니다. 이것은 일종의 깜박임이며 눈이 피로할 수 있을 것 같습니다. 일반적으로 픽던을 플레이하는데 마우스를 사용하기는 하지만 키보드를 사용하는 플레이어도 많기 때문에 이 깜박거림이 더욱 더 도드라집니다.
> 
> 유사한 로그라이크인 돌죽 등도 플레이어가 이동할 때 굳이 유저인터페이스를 disable 상태로 만들지는 않고, 픽던에서 플레이어가 이동하는 동안 사용자 인터페이스에 액세스하는 것이 사실상 불가능하기 때문에, 플레이어가 이동하는 동안 사용자 인터페이스를 굳이 깜박거리게 할 필요는 없어 보입니다. 이에 관련 코드 수정 검토를 요청 드립니다. 감사합니다.

Why not lower the brightness of your screen？

**Comment by starwindz** [comment]
> 활동 중 인터페이스의 비활성화 기능 자체는 SPD 본판의 시스템이라 UI 비활성화 시스템 자체의 제거를 원하시면 SPD 깃허브에 건의하시면 되고, 색깔의 문제라면 수정할 수 있습니다.

SPD 깃허브에 이를 이미 건의했지만 개발자는 비활성화 자체는 제거할 의사는 없고 단지 슬롯의 배경 자체를 다시 그리는 것 정도만 2.1버전에서 수정하겠다고 했습니다.

"색깔의 문제라면 수정이 가능"하다는 말씀은 Alpha 값 수정을 의미하는지요? 그렇다면 Alpha 값 수정으로 비활성화 자체가 구현가능하지 않을런지요?

**Comment by Hoto-Mocha** [comment]
'Alpha 값' 이라는 게 무엇을 의미하는지는 모르겠습니다만, 활성화된 UI와 비활성화된 UI 사이의 색깔 대비를 줄여 덜 깜빡이는 것처럼 보이게는 가능하다는 얘기입니다. 시스템 자체는 SPD의 것을 따라갈 생각입니다.

**Comment by starwindz** [comment]
> 'Alpha 값' 이라는 게 무엇을 의미하는지는 모르겠습니다만, 활성화된 UI와 비활성화된 UI 사이의 색깔 대비를 줄여 덜 깜빡이는 것처럼 보이게는 가능하다는 얘기입니다. 시스템 자체는 SPD의 것을 따라갈 생각입니다.

제가 말씀드린 "Alpha 값"은 배경을 투명하게 만드는 일종의 변수가 어딘가 있을 것 같다는 의미였습니다. 

그런데 말씀하신 "활성화된 UI와 비활성화된 UI 사이의 색깔 대비를 줄여 덜 깜빡이는 것처럼 보이게 한다"는 것이 제안드린 기능과 일치하는 방법으로 보입니다. 색깔 대비를 동일하게 하면 아예 깜빡거리지 않게 되지 않을까요?

**Comment by Hoto-Mocha** [comment]
원본 SPD에서 UI가 비활성화됨을 색깔로 나타내는 시스템을 사용하기 때문에, 색깔 대비를 같게 하고 싶지는 않습니다.

**Comment by starwindz** [comment]
> 원본 SPD에서 UI가 비활성화됨을 색깔로 나타내는 시스템을 사용하기 때문에, 색깔 대비를 같게 하고 싶지는 않습니다.

아, 알겠습니다. 말씀하신 "활성화된 UI와 비활성화된 UI 사이의 색깔 대비를 줄여 덜 깜빡이는 것처럼 보이게 한다"는 방식으로 다음 버전 업데이트 해주시면 좋을 것 같습니다. 감사합니다.

**Comment by Hoto-Mocha** [comment]
v2.58.0에서 기능 추가를 완료했습니다. 아이템 비활성화되는건 못 찾겠네요.

**Comment by starwindz** [comment]
이동 시 퀵슬롯 깜빡임 제거 옵션 ON되어 있을 때, 아이템도 적용될 수 있도록 해 보았습니다. 아래 fork의 code 참조 요청 드립니다.
https://github.com/starwindz/ARranged-Pixel-Dungeon/commit/8c38d983a1edeab580a6279e377f32351f148d18

그리고, "깜빡임"의 영어 표현은 "flickering"이 맞는 것 같습니다. (현재의 code에는 "flicking"으로 되어 있음)
