### ISSUE TITLE
The Spell_ Book of corruption cannot be read

### ISSUE THREAD

**Issue by nupnuts** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#328]
location：
com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.SpellBook_Corruption
missing “execute” method，found in 2.59 Source code(zip)

**Comment by Hoto-Mocha** [comment]
I will check while applying v2.1.0. thanks

**Comment by Hoto-Mocha** [comment]
Fixed in v2.61.0. thanks
