### ISSUE TITLE
Duelist Gun Ability

### ISSUE THREAD

**Issue by 0Alan-is** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#334]
## Essential Infomations(Use English Please)
Tried this but damn there's lot of bug. Tried Guns with Duelist/Champion but the Precision Shoot are bugged asf. I then crafted Assault rifle and it got bugged too. It only shoot 1 bullet instead of 3 so my damage lowered a lot compared to just using the machine gun. The Precision shoot also can't be turned off and it can't gain 1 charge back when it do the kill shot. Ended up died at yog due to the bugs.
- Version of the game(Ex.2.41.0) : 2.02
- [ ] Was your save created from previous version? N/A
- [ ] Did a crash occurs with the game? Yes
- About The Bug : 
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :

**Comment by Hoto-Mocha** [comment]
the version v2.02 is doesn't exsist in this game, please check again your version and be sure you have the latest version of the game.
