### ISSUE TITLE
Parry stance bug

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#335]
## Essential Infomations(Use English Please)
- Version of the game(Ex.2.41.0) : 2.61.0
- [ no] Was your save created from previous version?
- [ no] Did a crash occurs with the game?
- About The Bug : warrior can still use parry stance after transfer parry stance to second chance
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :

https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/assets/100021559/9297799c-c700-4fc5-99cf-c6c9e407a2a9

**Comment by Hoto-Mocha** [comment]
check the changelog of v2.62.0 and update it, please.
if the problem still occurs, write issue again. thanks.
