### ISSUE TITLE
전기공 수정 기획안(미정)

### ISSUE THREAD

**Issue by Hoto-Mocha** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#337]
대마법사(Wizard)

결투자와 동일하게 보조 무기로 마법서를 착용할 수 있음
마법서로 무기를 전환하지는 못하지만 장착 중인 마법서는 장착 중인 무기의 강화수치와 동일해짐
마법서를 장착 중일 경우 주 무기로 공격 시 마법서의 공격 효과가 발동
마법서를 여전히 읽을 수는 있으며, 적 공격 시 마법서의 쿨타임이 추가로 차감됨
마법서를 읽을 경우 지팡이에 부여된 마법 막대와 동일한 마법서의 읽는 효과가 추가로 발동되며, 동일한 마법일 경우 추가로 원소 폭발 효과를 발동

특성으로 추가 가능한 것
- 마법서를 읽는 시간이 0턴이 됨
- 마법서 쿨타임 감소
- 지팡이로 공격 시 전투 마법사 근접 공격 효과가 발동, 대신 충전량은 채워지지 않음
- 주문서 사용 시 마법서 쿨타임 추가 감소
- 마법 막대 사용 시 강화수치 및 특성 레벨에 비례한 확률로 대상에게 마법서 근접 공격 효과 부여

**Comment by nupnuts** [comment]
That looks awesome.

**Comment by Hoto-Mocha** [comment]
- [x] 대마법사
- [x] 마법이 부여되지 않은 빈 마법서에 무작위 마법을 부여할 수 있는 기능이 생김
- [x] 빈 마법서를 다른 마법서로 변환할 수 있는 기능이 생김
- [x] 챔피언과 비슷하게, 마법서만을 보조 무기로 착용 가능해짐
- [x] 마법서를 주 무기 및 보조 무기로 장착 중일 경우 주 무기, 투척 무기로 공격 시 마법서의 공격 효과가 발동
- [x] 붕괴의 마법서 리워크, 적 공격 시 일정 시간 동안 적이 어디에 있든 해당 적이 보이며 공격이 가능해짐
- [x] 붕괴의 마법서를 읽으면 공격 범위가 강화수치+1(최대 10칸)만큼 추가로 증가하는 버프를 얻도록 수정
- [x] 마법서를 읽을 경우 지팡이에 부여된 마법 막대와 동일한 마법서의 읽는 효과가 추가로 발동되며,
- [x] 동일한 마법일 경우 추가로 원소 폭발 효과를 발동
- [x] 3-7: 주문 강화
_+1:_ 주문서를 사용하면 마법서를 재사용 대기 시간 없이 추가로 _1번_ 읽을 수 있습니다.
_+2:_ 주문서를 사용하면 마법서를 재사용 대기 시간 없이 추가로 _2번_ 읽을 수 있습니다.
_+3:_ 주문서를 사용하면 마법서를 재사용 대기 시간 없이 추가로 _3번_ 읽을 수 있습니다.
- [x] 3-8: 영창 가속
_+1:_ 적을 물리 공격할 때마다 마법서의 재사용 대기 시간이 _2턴_씩 감소합니다.
_+2:_ +1의 효과에 더불어, 마법서를 읽는 데에 _턴을 소모하지 않습니다_.
_+3:_ +2의 효과에 더불어, 마법서를 읽을 때 3턴의 _아드레날린_을 얻습니다.
- [x] 3-9: 잔류 에너지
_+1:_ 적을 처치하면 17% 확률로 그 자리에 _충전_ 효과를 제공하는 지역이 짧게 생성됩니다.
_+2:_ 적을 처치하면 17% 확률로 그 자리에 _유물 충전_ 효과를 제공하는 지역이 짧게 생성됩니다.
_+3:_ 적을 처치하면 17% 확률로 그 자리에 _방어막 충전_ 효과를 제공하는 지역이 짧게 생성됩니다.
각 확률은 중복되지 않습니다.
- [x] 3-10: 전투 마법사의 혼
_+1:_ 마법사의 지팡이로 적을 공격하면 _33%_ 확률로 지팡이에 융합된 마법 막대의 효과에 따른 추가 효과 발동 확률이 적용됩니다.
_+2:_ 마법사의 지팡이로 적을 공격하면 _67%_ 확률로 지팡이에 융합된 마법 막대의 효과에 따른 추가 효과 발동 확률이 적용됩니다.
_+3:_ 마법사의 지팡이로 적을 공격하면 _100%_ 확률로 지팡이에 융합된 마법 막대의 효과에 따른 추가 효과 발동 확률이 적용됩니다.
- [x] 3-11: 흑마법사의 혼
_+1:_ 적에게 마법을 맞추면 _33%_ 확률로 영혼의 낙인을 부여하는 확률이 적용됩니다.
_+2:_ 적에게 마법을 맞추면 _67%_ 확률로 영혼의 낙인을 부여하는 확률이 적용됩니다.
_+3:_ 적에게 마법을 맞추면 _100%_ 확률로 영혼의 낙인을 부여하는 확률이 적용됩니다.
- [x] 3-11: 대마법사의 혼
_+1:_ 적에게 마법을 맞히면 맞힌 대상의 수와 사용한 충전량의 곱의 _1배_만큼 체력을 회복합니다.
_+2:_ 적에게 마법을 맞히면 맞힌 대상의 수와 사용한 충전량의 곱의 _2배_만큼 체력을 회복합니다.
_+3:_ 적에게 마법을 맞히면 맞힌 대상의 수와 사용한 충전량의 곱의 _3배_만큼 체력을 회복합니다.

**Comment by Hoto-Mocha** [comment]
- [ ] 3-7: 주문 강화
_+1:_ 주문서를 사용하면 마법서를 재사용 대기 시간 없이 추가로 _1번_ 읽을 수 있습니다.\n_+2:_ 주문서를 사용하면 마법서를 재사용 대기 시간 없이 추가로 _2번_ 읽을 수 있습니다.\n_+3:_ 주문서를 사용하면 마법서를 재사용 대기 시간 없이 추가로 _3번_ 읽을 수 있습니다.
- [ ] 3-8: 영창 가속
_+1:_ 적을 물리 공격할 때마다 마법서의 재사용 대기 시간이 _2턴_씩 감소합니다.\n+2:_ +1의 효과에 더불어, 마법서를 읽는 데에 _턴을 소모하지 않습니다_.\n+3:_ +2의 효과에 더불어, 마법서를 읽을 때 3턴의 _아드레날린_을 얻습니다.
- [ ] 3-9: 잔류 에너지
_+1:_ 적을 처치하면 17% 확률로 그 자리에 _충전_ 효과를 제공하는 지역이 짧게 생성됩니다.\n+2:_ 적을 처치하면 17% 확률로 그 자리에 _유물 충전_ 효과를 제공하는 지역이 짧게 생성됩니다.\n+3:_ 적을 처치하면 17% 확률로 그 자리에 _방어막 충전_ 효과를 제공하는 지역이 짧게 생성됩니다.\n각 확률은 중복되지 않습니다.
- [ ] 3-11: 전투 마법사의 혼
_+1:_ 마법사의 지팡이로 적을 공격하면 _33%_ 확률로 지팡이에 융합된 마법 막대의 효과에 따른 추가 효과 발동 확률이 적용됩니다.\n+2:_ 마법사의 지팡이로 적을 공격하면 _67%_ 확률로 지팡이에 융합된 마법 막대의 효과에 따른 추가 효과 발동 확률이 적용됩니다.\n+3:_ 마법사의 지팡이로 적을 공격하면 _100%_ 확률로 지팡이에 융합된 마법 막대의 효과에 따른 추가 효과 발동 확률이 적용됩니다.
- [ ] 3-12: 흑마법사의 혼
_+1:_ 적에게 마법을 맞추면 _33%_ 확률로 영혼의 낙인을 부여하는 확률이 적용됩니다.\n+2:_ 적에게 마법을 맞추면 _67%_ 확률로 영혼의 낙인을 부여하는 확률이 적용됩니다.\n+3:_ 적에게 마법을 맞추면 _100%_ 확률로 영혼의 낙인을 부여하는 확률이 적용됩니다.
- [ ] 3-10: 대마법사의 혼
_+1:_ 적에게 마법을 맞추면 _33%_ 확률로 대상에게 마법서의 근접 공격 추가 효과가 발동합니다.\n+2:_ 적에게 마법을 맞추면 _67%_ 확률로 대상에게 마법서의 근접 공격 추가 효과가 발동합니다.\n_+3:_ 적에게 마법을 맞추면 _100%_ 확률로 대상에게 마법서의 근접 공격 추가 효과가 발동합니다.
