### ISSUE TITLE
English translation bug

### ISSUE THREAD

**Issue by sjsxmd** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#338]
## Essential Infomations(Use English Please)
- Version of the game(Ex.2.41.0) : 2.63.0
- [ no] Was your save created from previous version?
- [no ] Did a crash occurs with the game?
- About The Bug : 
- Bug Occurrence Conditions : 

## Optional Infomations
- Screenshot :
![Screenshot_20230713_083836_com arrangedpixel arrangedpixeldungeon](https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/assets/100021559/136a989f-02a1-4198-8384-38052213484f)
![Screenshot_20230713_083848_com arrangedpixel arrangedpixeldungeon](https://github.com/Hoto-Mocha/ARranged-Pixel-Dungeon/assets/100021559/c292283a-3d10-46b4-9ba3-967f39018cc7)

**Comment by Hoto-Mocha** [comment]
Fixed in v2.64.0
