### ISSUE TITLE
6단계 무기 드랍 버그 

### ISSUE THREAD

**Issue by YouIG** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#98]
## 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 체크박스가 있는 문항의 경우 체크를 원하시면 [ ] 를 [x]로 바꿔 주시면 됩니다.
5. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
6. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
7. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.25.0) :  1.27.0
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요? 

현재 버전에서 새롭게 시작한 세이브입니다. 

- [ ] 게임에 크래시가 발생했나요(튕겼나요)?

아니요. 

- 버그 내용 : 

6단계 무기 필드 드랍

- 버그 발생 조건('모름'일 경우 빠른 해결에 어려움이 있습니다) : 

모름. 

## 선택 정보
- 스크린샷  #첨부
![Screenshot_20220109-030546](https://user-images.githubusercontent.com/97358481/148655121-70b107f4-e920-42bf-903c-150380e7c38f.png)

**Comment by Hoto-Mocha** [comment]
![Screenshot_20220109-163617.jpg](https://user-images.githubusercontent.com/76470428/148673576-05febab5-8549-48fa-851d-a2f2191fb1af.jpg)
아무리 드랍을 시켜봐도 6티어는 단 한개도 안 떨어지니 조건이 확인될 때까지 보류하겠음

**Comment by YouIG** [comment]
그동안 갤에 올라왔던 버그 제보도 보면 몬스터 드랍 보다는 필드 드랍으로 먹은 경우가 대부분이라 필드 자연 드랍에 문제가 있는 것으로 보입니다.

**Comment by Hoto-Mocha** [comment]
일단 시스템 자체를 뜯어고치는 방식으로 수정을 하긴 했는데, 아직도 원인이 정확하게 파악되지 않은 상태여서 앞으로 6티어가 떨어지는 계속해서 지켜봐야 할 듯

**Comment by YouIG** [comment]
수고하셨습니다.
