### ISSUE TITLE
식물학자 자연의 샌들 드랍 문제 

### ISSUE THREAD

**Issue by YouIG** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#99]
## 이슈 작성 전 참고사항
1. 총픽던은 업데이트 이후 '새로운' 세이브를 만들어서 플레이하는 것을 권장합니다. 현재보다 이전 버전에서 만들어진 세이브를 업데이트 이후에 플레이했을 때 발생하는 버그는 해결에 어려움이 있습니다.
2. 이슈 작성 전 같은 내용의 열린 이슈가 있는지 확인 부탁드립니다. 만약 같은 내용이 있다면 그 이슈의 코멘트(댓글)로 내용을 추가해주시기 바랍니다.
3. 버그 조건은 정확할 수록 좋습니다.
4. 체크박스가 있는 문항의 경우 체크를 원하시면 [ ] 를 [x]로 바꿔 주시면 됩니다.
5. 참고사항을 제대로 읽지 않아 템플릿이 지켜지지 않은 경우에는 제대로 된 답변이 불가능하며, 이에 따라 이슈가 답변 없이 닫힐 수 있다는 점을 알려드립니다.
6. 게임이 최신버전이 아닐 경우 업데이트를 먼저 해 주시기 바랍니다.
7. 말투는 자유입니다. 반말을 쓰든, 존댓말을 쓰든 상관 없습니다.

## 필수 정보
- 게임의 버전(Ex.1.25.0) : 1.27.0
- [ ] 버그가 발생한 세이브가 현재보다 이전 버전에서 만들어진 것인가요?
- [ ] 게임에 크래시가 발생했나요(튕겼나요)?
- 버그 내용 : 식물학자 플레이 중 자연의 샌들이 수정 상자 미믹에서 나옵니다. 
- 버그 발생 조건('모름'일 경우 빠른 해결에 어려움이 있습니다) : 모름. 
![Screenshot_20220109-082844](https://user-images.githubusercontent.com/97358481/148663421-b91e3b0e-124f-4b29-b8fb-d25a25ef8670.png)

## 선택 정보
- 스크린샷 첨부

**Comment by Hoto-Mocha** [comment]
수정 예정

- [ ] Generator.java에서 식물학자일 경우에 다른 드랍률을 적용하도록 변경

**Comment by Hoto-Mocha** [comment]
수정 시도 결과 현재 기술적으로 불가능함을 확인, 보류해 놓겠음.
